name: Integrate External Repositories

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to commit to (e.g., feature/distributed-atomspace-integration)'
        required: true
        default: 'feature/distributed-atomspace-integration'

jobs:
  integrate_repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }} # Checkout the specified branch
        token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for write access

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create integrations directory
      run: mkdir -p integrations

    - name: Clone node9 repository
      run: git clone https://github.com/drzo/node9.git integrations/node9_temp

    - name: Remove node9 git history
      run: rm -rf integrations/node9_temp/.git

    - name: Move node9 to final location
      run: |
        if [ ! -d integrations/node9 ]; then
          mv integrations/node9_temp integrations/node9
          echo "Move completed: node9_temp → node9"
        else
          echo "Skip: integrations/node9 already exists"
        fi

    - name: Clone mem0 repository
      run: git clone https://github.com/drzo/mem0.git integrations/mem0_temp

    - name: Remove mem0 git history
      run: rm -rf integrations/mem0_temp/.git

    - name: Move mem0 to final location
      run: |
        if [ ! -d integrations/mem0 ]; then
          mv integrations/mem0_temp integrations/mem0
          echo "Move completed: mem0_temp → mem0"
        else
          echo "Skip: integrations/mem0 already exists"
        fi

    - name: Clone ggml-org-central repository
      run: git clone https://github.com/ZoneCog/ggml-org-central.git integrations/ggml-org-central_temp

    - name: Remove ggml-org-central git history
      run: rm -rf integrations/ggml-org-central_temp/.git

    - name: Move ggml-org-central to final location
      run: |
        if [ ! -d integrations/ggml-org-central ]; then
          mv integrations/ggml-org-central_temp integrations/ggml-org-central
          echo "Move completed: ggml-org-central_temp → ggml-org-central"
        else
          echo "Skip: integrations/ggml-org-central already exists"
        fi

    - name: Clone kokkos-central repository
      run: git clone https://github.com/ZoneCog/kokkos-central.git integrations/kokkos-central_temp

    - name: Remove kokkos-central git history
      run: rm -rf integrations/kokkos-central_temp/.git

    - name: Move kokkos-central to final location
      run: |
        if [ ! -d integrations/kokkos-central ]; then
          mv integrations/kokkos-central_temp integrations/kokkos-central
          echo "Move completed: kokkos-central_temp → kokkos-central"
        else
          echo "Skip: integrations/kokkos-central already exists"
        fi

    - name: Clone a0ml repository
      run: git clone https://github.com/ZoneCog/a0ml.git integrations/a0ml_temp

    - name: Remove a0ml git history
      run: rm -rf integrations/a0ml_temp/.git

    - name: Move a0ml to final location
      run: |
        if [ ! -d integrations/a0ml ]; then
          mv integrations/a0ml_temp integrations/a0ml
          echo "Move completed: a0ml_temp → a0ml"
        else
          echo "Skip: integrations/a0ml already exists"
        fi

    - name: Clone mlpn repository
      run: git clone https://github.com/OzCog/mlpn.git integrations/mlpn_temp

    - name: Remove mlpn git history
      run: rm -rf integrations/mlpn_temp/.git

    - name: Move mlpn to final location
      run: |
        if [ ! -d integrations/mlpn ]; then
          mv integrations/mlpn_temp integrations/mlpn
          echo "Move completed: mlpn_temp → mlpn"
        else
          echo "Skip: integrations/mlpn already exists"
        fi

    - name: Add integrated repositories to Git
      run: git add integrations/

    - name: Commit integrated repositories
      run: |
        git commit -m "feat: Integrate node9 and mem0 repositories

        This commit adds the full source code of node9 and mem0
        into the 'integrations/' directory, with their respective
        git histories removed to create a clean, unified codebase.

        This action is designed to handle large file integrations
        that might otherwise cause issues with direct pushes.

        Co-authored-by: drzo <d@rzo.io>"
      env:
        GIT_COMMITTER_NAME: GitHub Actions
        GIT_COMMITTER_EMAIL: actions@github.com

    - name: Push changes
      run: git push origin ${{ github.event.inputs.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for push
